# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:latest  # Use a prebuilt NGINX image
#           ports:
#             - containerPort: 80



# -----------next file -----

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location /world {
          alias /usr/share/nginx/html/world;
        }
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello from GJS</title>
    </head>
    <body>
      <h1>Hello from GJS</h1>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: default
  annotations:
    argocd.argoproj.io/tracking-id: my-argocd-application:apps/Deployment:default/nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:gjss
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /usr/share/nginx/html/world/index.html
              subPath: index.html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
